on:
  push:
    branches:
      - master
      - feat/aarch64 # DO NOT MERGE
name: Upgrade AWS
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  prepare-ecr:
    name: Prepare ECR
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/prod' || github.ref == 'refs/heads/feat/aarch64' # DO NOT MERGE
    timeout-minutes: 1
    outputs:
      role: ${{ steps.prepare.outputs.role }}
      branch: ${{ steps.prepare.outputs.branch }}
    steps:
      - name: Prepare
        id: prepare
        run: |
          case ${{github.ref}} in
            refs/heads/master)
              role=arn:aws:iam::983851922138:role/GHA,tippecanoe
              branch=master
              ;;
            refs/heads/prod)
              role=arn:aws:iam::983851922138:role/GHA,tippecanoe
              branch=prod
              ;;
            refs/heads/feat/aarch64) # DO NOT MERGE
              role=arn:aws:iam::983851922138:role/GHA,tippecanoe
              branch=master
              ;;
            *)
              echo "Unknown ref: ${{github.ref}}"
              exit 1
              ;;
          esac
          echo branch: $branch
          echo role: $role
          echo "::set-output name=branch::$branch"
          echo "::set-output name=role::$role"
  ecr:
    name: ECR
    runs-on: ubuntu-latest
    needs: [prepare-ecr]
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: aws-actions/configure-aws-credentials@v1
        name: Configure AWS Credentials (eu-central-1)
        with:
          role-to-assume: ${{needs.prepare-ecr.outputs.role}}
          aws-region: eu-central-1
          role-duration-seconds: 900
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: "Build & Push (amd64, arm64)"
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t 983851922138.dkr.ecr.eu-central-1.amazonaws.com/tippecanoe:latest \
            --push .
